config/routes.rb
Rails.application.routes.draw do
  resources :towits do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/towit.rb
class Towit < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/towits_controller.rb
class TowitsController < ApplicationController
  before_action :set_towit, only: [:show, :edit, :update, :destroy]
  def index
    @towits = Towit.all
  end

  def new
    @towit = Towit.new
  end

  def show
  end

  def edit
  end

  def create
   @towit = Towit.new(towit_params)
   respond_to do |format|
    if @towit.save
      format.html { redirect_to @towit, notice: 'The tweet was created SUCCESSFULLY.' }
      format.json { render :show, status: :created, location: @towit }
    else
     format.html { render :new }
      format.json { render json: @towit.errors, status: :unprocessable_entity }
    end
  end
  end

  def confirm
    @towit = Towit.new(towit_params)
  end

  def update
    if @towit.update(towit_params)
      redirect_to @towit,
      notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @towit.destroy
    redirect_to towits_path, notice: "twit deleted!"
  end

  private
  def set_towit
    @towit = Towit.find(params[:id])
  end
  def towit_params
    params.require(:towit).permit(:content)
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/towits_helper.rb
module TowitsHelper
  def choose_new_or_edit
        if action_name == 'new'
            confirm_towits_path
        elsif action_name == 'edit'
            towit_path
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Towits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/towits/_form.html.erb
<%= form_with(model: towit, local: true, url: choose_new_or_edit) do |form| %>
  <% if towit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(towit.errors.count, "error") %> prohibited this towit from being saved:</h2>

      <ul>
        <% towit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/towits/confirm.html.erb
<body class= "body">
<h3>Send with the following Content</h3>

<%= form_with(model: @towit, url: towits_path, local: true) do |form| %>
    <%= form.hidden_field :content %>

    <p>Body:<%= @towit.content %></p>
  <%= form.submit  "Submit" %>
<% end %>
</body>

app/views/towits/edit.html.erb
<body class= "body">
<h1>Editing Towit</h1>

<%= render 'form', towit: @towit %>

<%= link_to 'Show', @towit %> |
<%= link_to 'Back', towits_path %>
</body>

app/views/towits/index.html.erb
<body class= "body">
  <p><%= notice %></p>
    <%= stylesheet_link_tag "towits" %>
    <%= stylesheet_link_tag "normalize" %>
    <header class= "header">
    <p class= "logo"><%= image_tag("logoo.png") %> </p>
    </header>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @towits.each do |towit| %>
      <tr>
        <td><%= towit.content %></td>
      </tr>
      <br>
      <tr>
        <td ><%= link_to 'Show', towit %></td>
      </tr>
      <tr>
        <td><%= link_to 'Edit', edit_towit_path(towit) %></td>
      </tr>
        <td><%= link_to 'Delete', towit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <br>
     <td  width="20%" valign="left" bgcolor="pink"> <%= link_to 'Post a new towit', new_towit_path  %> </td>
  </tbody>
</table>

<br>
<footer>
<p class="left">© 2020 Copyright</p>
  <ul>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <li a href="#" class="fa fa-facebook"></li></a>
    <li a href="#" class="fa fa-twitter"></li></a>
    <li a href="#" class="fa fa-youtube"></li></a>
    <li a href="#" class="fa fa-linkedin"></li></a>
  </ul>
</footer>
</body>

app/views/towits/new.html.erb
<body class= "body">
<h1>New Towit</h1>

<%= render 'form', towit: @towit %>

<%= link_to 'Back', towits_path %>
</body>

app/views/towits/show.html.erb
<body>
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @towit.content %>
</p>

<%= link_to 'Edit', edit_towit_path(@towit) %> |
<%= link_to 'Back', towits_path %>
</body>